---
- name: AWS ALB ingress controller
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: deploy an alb ingress controller
      k8s:
        api_version: v1
        definition:
          kind: Deployment
          metadata:
            labels:
              app.kubernetes.io/component: controller
              app.kubernetes.io/name: aws-load-balancer-controller
            name: aws-load-balancer-controller
            namespace: kube-system
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/component: controller
                app.kubernetes.io/name: aws-load-balancer-controller
            template:
              metadata:
                labels:
                  app.kubernetes.io/component: controller
                  app.kubernetes.io/name: aws-load-balancer-controller
              spec:
                containers:
                  - args:
                      - --cluster-name=terraform-eks-demo
                      - --ingress-class=alb
                    image: amazon/aws-alb-ingress-controller:v2.1.0
                    livenessProbe:
                      failureThreshold: 2
                      httpGet:
                        path: /healthz
                        port: 61779
                        scheme: HTTP
                      initialDelaySeconds: 30
                      timeoutSeconds: 10
                    name: controller
                    ports:
                      - containerPort: 9443
                        name: webhook-server
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 200m
                        memory: 500Mi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      runAsNonRoot: true
                    volumeMounts:
                      - mountPath: /tmp/k8s-webhook-server/serving-certs
                        name: cert
                        readOnly: true
                securityContext:
                  fsGroup: 1337
                serviceAccountName: alb-ingress-controller
                terminationGracePeriodSeconds: 10
                volumes:
                  - name: cert
                    secret:
                       defaultMode: 420
                       secretName: aws-load-balancer-webhook-tls

