---
- name: deployment with ingress
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create pod for deploy and service
      k8s:
        api_version: apps/v1
        definition:
          kind: Deployment
          metadata:
            namespace: game-2048
            name: deployment-2048
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: app-2048
            replicas: 1
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: app-2048
              spec:
                containers:
                  - name: "2048"
                    image: alexwhen/docker-2048
                    ports:
                    - containerPort: 80
                      protocol: TCP

    - name: Create a service object
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: game-2048
            name: service-2048
          spec:
            ports:
              - port: 80
                targetPort: 80
                protocol: TCP
            type: NodePort
            selector:
              app.kubernetes.io/name: app-2048

    - name: Create an ingress
      k8s:
        name: create an ingress
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            namespace: game-2048
            name: ingress-2048
            annotations:
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
          spec:
            rules:
            - http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: service-2048
                      port: 
                        number: 80        
