apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: your-cluster-name
  region: your-region

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        albIngress: true  # Example of enabling ALB Ingress controller IAM policy

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::536233321899:policy/AWSLoadBalancerControllerIAMPolicy

